const projectsData = [
    {
        id: 'qhse',
        title: 'Quality, Health, Safety, & Environmental Platform (QHSE Sphere System)',
        short_title: 'QHSE Sphere Platform',
        version: 'V2.2.14',
        category: 'Professional',
        shortDesc: 'Enterprise QHSE platform used daily by 400+ users across 3+ organizations, spanning 30+ modules.',
        fullDesc: 'Built and maintained an enterprise QHSE platform used daily by 400+ people across 3+ organizations, spanning 30+ modules that digitalized incident, accident, and equipment-fault reporting for entire departments. Cut manual reporting and procedure-completion time by 70% through automated workflows: digital signatures, role-based authorization, and automated email/notification chains. Integrated with in-house departmental ticketing APIs to route issues directly to the responsible team.',
        github: '-',
        stack: [
            { icon: 'php', name: 'PHP' },
            { icon: 'nodedotjs', name: 'Node.js' },
            { icon: 'docker', name: 'Docker' },
            { icon: 'mysql', name: 'MySQL' },
            { icon: 'javascript', name: 'JavaScript' },
            { icon: 'html5', name: 'HTML5' },
            { icon: 'css', name: 'CSS' },
            { icon: 'n8n', name: 'n8n' },
            { icon: 'Git', name: 'Git' },
            { icon: 'githubactions', name: 'GitHub Actions' },
        ],
        images: [
            'assets/projects/professional/QHSE_2026_Screenshots/1.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/3.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/6.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/8.jpg',
        ],
    },
    {
        id: 'cmms',
        title: 'Computerized Maintenance Management System (CMMS) Platform',
        short_title: 'CMMS Platform',
        version: 'V2.0.6',
        category: 'Professional',
        shortDesc: 'Comprehensive CMMS Platform used daily by maintenance teams across multiple organizations, spanning 20+ modules.',
        fullDesc: 'Built and maintained an enterprise CMMS Platform designed for enterprise asset management, maintenance planning, and operational control. Supports preventive and corrective maintenance workflows, work order and cost tracking, rental equipment management with digital signatures, and personnel, contract, and technician assignment. Includes custom QR code generation for asset identification, automated reporting of upcoming and overdue maintenance, analytics-driven maintenance scheduler, and integrated email notifications to reduce downtime and improve operational efficiency.',
        github: '-',
        stack: [
            { icon: 'php', name: 'PHP' },
            { icon: 'nodedotjs', name: 'Node.js' },
            { icon: 'mysql', name: 'MySQL' },
            { icon: 'javascript', name: 'JavaScript' },
            { icon: 'html5', name: 'HTML5' },
            { icon: 'css', name: 'CSS' },
            { icon: 'n8n', name: 'n8n' },
            { icon: 'Git', name: 'Git' },
            { icon: 'githubactions', name: 'GitHub Actions' },
        ],
        images: [
            'assets/projects/professional/CMMS_Updated_2025/1.jpg',
            'assets/projects/professional/CMMS_Updated_2025/6.jpg',
            'assets/projects/professional/CMMS_Updated_2025/7.jpg',
            'assets/projects/professional/CMMS_Updated_2025/10.jpg',
        ],
    },
    {
        id: 'cmms-k8s',
        title: 'Computerized Maintenance Management System (CMMS) on Kubernetes',
        short_title: 'CMMS on Kubernetes',
        version: 'V1.0.3',
        category: 'Personal',
        shortDesc: 'Self-hosted maintenance management system running on Kubernetes.',
        fullDesc: 'Self-hosted maintenance management system running on Kubernetes. Went through two independent code reviews, built a 7-day remediation roadmap for the critical findings, and added Prometheus/Discord alerting through an Alertmanager proxy.',
        github: 'https://github.com/GeorgeArgyris/REPLACE',
        stack: [
            { icon: 'kubernetes', name: 'Kubernetes' },
            { icon: 'docker', name: 'Docker' },
            { icon: 'postgresql', name: 'PostgreSQL' },
            { icon: 'prometheus', name: 'Prometheus' },
        ],
        images: [
            'assets/projects/personal/cmms/1.jpg',
            'assets/projects/personal/cmms/2.jpg',
            'assets/projects/personal/cmms/3.jpg',
            'assets/projects/personal/cmms/4.jpg',
        ],
    },
];