const projectsData = [
    {
        id: 'qhse',
        title: 'Quality, Health, Safety, & Environmental Platform (QHSE Sphere System)',
        short_title: 'QHSE Sphere Platform',
        version: 'V2.2.14',
        category: 'Professional',
        shortDesc: 'Enterprise QHSE platform used daily by 400+ users across 3+ organizations, spanning 30+ modules.',
        fullDesc: 'Built and maintained an enterprise QHSE platform used daily by 400+ people across 3+ organizations, spanning 30+ modules that digitalized incident, accident, and equipment-fault reporting for entire departments. Cut manual reporting and procedure-completion time by 70% through automated workflows: digital signatures, role-based authorization, and automated email/notification chains. Integrated with in-house departmental ticketing APIs to route issues directly to the responsible team.',
        github: '-',
        stack: [
            { icon: 'php', name: 'PHP' },
            { icon: 'nodedotjs', name: 'Node.js' },
            { icon: 'docker', name: 'Docker' },
            { icon: 'mysql', name: 'MySQL' },
            { icon: 'javascript', name: 'JavaScript' },
            { icon: 'html5', name: 'HTML5' },
            { icon: 'css', name: 'CSS' },
            { icon: 'n8n', name: 'n8n' },
            { icon: 'Git', name: 'Git' },
            { icon: 'githubactions', name: 'GitHub Actions' },
        ],
        images: [
            'assets/projects/professional/QHSE_2026_Screenshots/1.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/3.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/6.jpg',
            'assets/projects/professional/QHSE_2026_Screenshots/8.jpg',
        ],
    },
    {
        id: 'cmms',
        title: 'Computerized Maintenance Management System (CMMS) Platform',
        short_title: 'CMMS Platform',
        version: 'V2.0.6',
        category: 'Professional',
        shortDesc: 'Comprehensive CMMS Platform used daily by maintenance teams across multiple organizations, spanning 20+ modules.',
        fullDesc: 'Built and maintained an enterprise CMMS Platform designed for enterprise asset management, maintenance planning, and operational control. Supports preventive and corrective maintenance workflows, work order and cost tracking, rental equipment management with digital signatures, and personnel, contract, and technician assignment. Includes custom QR code generation for asset identification, automated reporting of upcoming and overdue maintenance, analytics-driven maintenance scheduler, and integrated email notifications to reduce downtime and improve operational efficiency.',
        github: '-',
        stack: [
            { icon: 'php', name: 'PHP' },
            { icon: 'nodedotjs', name: 'Node.js' },
            { icon: 'mysql', name: 'MySQL' },
            { icon: 'javascript', name: 'JavaScript' },
            { icon: 'html5', name: 'HTML5' },
            { icon: 'css', name: 'CSS' },
            { icon: 'n8n', name: 'n8n' },
            { icon: 'Git', name: 'Git' },
            { icon: 'githubactions', name: 'GitHub Actions' },
        ],
        images: [
            'assets/projects/professional/CMMS_Updated_2025/1.jpg',
            'assets/projects/professional/CMMS_Updated_2025/6.jpg',
            'assets/projects/professional/CMMS_Updated_2025/7.jpg',
            'assets/projects/professional/CMMS_Updated_2025/10.jpg',
        ],
    },
    {
        id: 'rpa',
        title: 'Invoice LLM Automation Tool',
        short_title: 'Invoice LLM Automation Tool',
        version: 'V1.0.4',
        category: 'Professional',
        shortDesc: 'An automated pipeline that scans an Office 365 mailbox via Microsoft Graph API, extracts invoices from attachments, portal links, or JS-rendered pages (via Playwright), and uses an LLM to convert them into structured data.',
        fullDesc: 'Developed an automated invoice-processing pipeline that connects to an Office 365 mailbox via OAuth2/Microsoft Graph API to scan incoming email for invoices. It uses a layered extraction strategy, parsing PDF attachments, following vendor portal links, and falling back to a headless Playwright browser for JavaScript-rendered pages, then passes extracted text to an LLM (OpenAI/Groq) to produce structured invoice data (number, vendor, date, balance, line items). Scans run asynchronously in the background with live progress tracking and a persistent cache to avoid reprocessing.',
        github: '-',
        stack: [
            { icon: 'python', name: 'Python' },
            { icon: 'flask', name: 'Flask' },
            { icon: 'auth0', name: 'OAuth2' },
            { icon: 'huggingface', name: 'OpenAI API' },
            { icon: 'googlechrome', name: 'Headless Browser' },
            { icon: 'github', name: 'GitHub' },
            {icon: 'html5', name:'HTML5'},
        ],
        images: [
            'assets/projects/professional/rpa_Screenshots/1.jpg',
            'assets/projects/professional/rpa_Screenshots/2.jpg',
            'assets/projects/professional/rpa_Screenshots/3.jpg',
            'assets/projects/professional/rpa_Screenshots/diagram.png',
        ],
    },
    {
    id: 'recipe-mng',
    title: 'Recipe Management Tool',
    short_title: 'Recipe Management Tool',
    version: 'V1.1.3',
    category: 'Professional',
    shortDesc: 'A .NET tool embedded inside a WinCC HMI interface for managing product recipes and materials at a pipe manufacturing company, connected to a web API for analytics and a live, color-coded grid for error tracking.',
    fullDesc: 'Developed a .NET application embedded within the WinCC industrial interface, enabling operators to create, update, and complete production recipes and materials for products manufactured by a pipe production line. The tool integrates with a backend web API to feed analytics and displays a live data grid where rows are color-coded based on error/status records, giving operators immediate visual feedback on recipe or material issues during production.',
    github: '-',
    stack: [
        { icon: 'dotnet', name: '.NET' },
        { icon: 'sharp', name: 'C#' },
        { icon: 'html5', name: 'HTML5' },
        { icon: 'css', name: 'CSS3' },
        { icon: 'dotnet', name: 'Web API' },
        { icon: 'mysql', name: 'Microsoft SQL Server' },
    ],
    images: [
        'assets/projects/professional/Project_Palaplast_Net/Palaplast_1.png',
        'assets/projects/professional/Project_Palaplast_Net/Palaplast_2.png',
        'assets/projects/professional/Project_Palaplast_Net/Palaplast_3.png',
        'assets/projects/professional/Project_Palaplast_Web/Web_Palaplast_Page2_3.png',
    ],
},
    {
        id: 'digital-twin',
        title: 'Digital Twin Model based on Neural Complex Event Recognition for Industrial Electrical Systems',
        short_title: 'Digital Twin Model (N-CER)',
        version: 'Thesis',
        category: 'Personal',
        shortDesc: 'Digital Twin model for industrial electrical systems based on neural complex-event recognition, built as part of a master’s thesis.',
        fullDesc: 'Full-stack real-time monitoring framework built around a 3D digital twin. A streaming pipeline ingests live sensor data and a neural complex-event recognition model flags patterns in the stream, surfacing them back onto the 3D scene as they happen.',
        github: 'https://github.com/GeorgeArgyris/REPLACE',
        stack: [
            { icon: 'unity', name: 'Unity Engine' },
            { icon: 'python', name: 'Python' },
            { icon: 'openjdk', name: 'Java' },
            { icon: 'apachekafka', name: 'Kafka' },
            { icon: 'apacheflink', name: 'Flink' },
            { icon: 'docker', name: 'Docker' },
            { icon: 'pytorch', name: 'PyTorch' },
            { icon: 'tensorflow', name: 'TensorFlow' },
            { icon: 'sharp', name: 'C#' },
            { icon: 'neutralinojs', name: 'TimeGAN neural network' },
            { icon: 'neutralinojs', name: 'LSTM neural network' },
        ],
        images: [
            'assets/projects/personal/DigitalTwin/8.jpg',
            'assets/projects/personal/DigitalTwin/4.jpg',
            'assets/projects/personal/DigitalTwin/9.jpg',
            'assets/projects/personal/DigitalTwin/BasicArchtectureDiagramDiplomaThesis.jpg',
        ],
    },
    {
        id: 'cmms-k8s',
        title: 'Computerized Maintenance Management System (CMMS) on Kubernetes',
        short_title: 'CMMS on Kubernetes',
        version: 'V1.0.3',
        category: 'Personal',
        shortDesc: 'Self-hosted maintenance management system running on Kubernetes.',
        fullDesc: 'Self-hosted maintenance management system running on Kubernetes. Went through two independent code reviews, built a 7-day remediation roadmap for the critical findings, and added Prometheus/Discord alerting through an Alertmanager proxy.',
        github: 'https://github.com/GeorgeArgyris/REPLACE',
        stack: [
            { icon: 'kubernetes', name: 'Kubernetes' },
            { icon: 'docker', name: 'Docker' },
            { icon: 'postgresql', name: 'PostgreSQL' },
            { icon: 'prometheus', name: 'Prometheus' },
        ],
        images: [
            'assets/projects/personal/cmms/1.jpg',
            'assets/projects/personal/cmms/2.jpg',
            'assets/projects/personal/cmms/3.jpg',
            'assets/projects/personal/cmms/4.jpg',
        ],
    },
];