const stack = [
            { name: "PHP", icon: "php" },
            { name: "MySQL", icon: "mysql" },
            { name: "Python", icon: "python" },
            { name: "JavaScript", icon: "javascript" },
            { name: "HTML", icon: "html5" },
            { name: "CSS", icon: "css" },
            { name: "React", icon: "react" },
            { name: "Node.js", icon: "nodedotjs" },
            { name: "FastAPI", icon: "fastapi" },
            { name: "C", icon: "c" },
            { name: "Java", icon: "openjdk" },
            { name: "Scala", icon: "scala" },
            { name: "Docker", icon: "docker" },
            { name: "Kubernetes", icon: "kubernetes" },
            { name: "GitHub Actions", icon: "githubactions" },
            { name: "Git", icon: "git" },
            { name: ".NET", icon: "dotnet" },
            { name: "Unity", icon: "unity" },
            { name: "Kafka", icon: "apachekafka" },
            { name: "Flink", icon: "apacheflink" },
            { name: "Spark", icon: "apachespark" },
            { name: "PyTorch", icon: "pytorch" },
            { name: "TensorFlow", icon: "tensorflow" },
            { name: "n8n", icon: "n8n" },
            { name: "Prometheus", icon: "prometheus" },
            { name: "Grafana", icon: "grafana" },
            { name: "Tailwind CSS", icon: "tailwindcss" },
            { name: "Linux", icon: "linux" },
            { name: "Neural Networks", icon: "neutralinojs" },
            { name: "Inno Setup", icon: "setapp" },
            { name: "C#", icon: "sharp" },
        ];